name: EpicSpawners
description: EpicSpawners
version: 5.4
depend: [Arconix, Vault]
softdepend: [Towny, RedProtect Kingdoms, PlotSquared, GriefPrevention, USkyBlock, ASkyBlock, WorldGuard, Factions, PlaceholderAPI]
main: com.songoda.epicspawners.EpicSpawnersPlugin
author: songoda
commands:
  EpicSpawners:
    description: I have no idea.
    default: true
    aliases: [es]
    usage: /<command> [reload]
  SpawnerStats:
    description: I have no idea.
    default: false
    usage: /<command> [reload]
  SpawnerShop:
    description: I have no idea.
    default: false
    usage: /<command> [reload]